language: python
python:
- 3.4.4
install:
- pip install .
script:
- python setup.py test
env:
  global:
  - secure: H69Xdvd5J5T1FI+R5J7rMCC5zjEWWVVJZwQcsVfz+8dstAXG/HQgSsPdOj2NmOYP7seihj6dlylJCuOGXYJQvet4mqn+09t6skXHYSZ6nQwDp3iyM7ak5xXBSpFi419LjVd9uFqadrG22hMkxrctLiRhLaDV+PTvjFWuKO1gacnNfdICrr9RE/kmAzzPeIrZ+EcaFJsusBbtInorAtOb53xiQBtJWU72cyWw7ldKo9CJNlmcAqmgy1FoqQgGbd7icFsgn4gIad3F2QXFj6egfB/JcnRXsqPA4oizaoCItvXObMqGEXmgkVHU2oMZvTbCzONPrv0cTlcvK9r+ef0oAOzo4BWsAI2Mqd7SLBIa11B1e+pAhvjlSHOR5QZbo7xI1OmhIBQSrRRqgckAmqRFIHGxQfWXAcGkValXhitFoC7SDb/d4NqOOsDXZqjka7sYG15BDWr9C8sFTCSf2p8TIAcIT+YmdLNkBr6ntS2BXNG/wdEv1EHd5Zg/CGKeYijbyKdw9c9xXK5G2sKvKxnDxQgV1qrNctX0n8FhgbhzhLAG6e4Ci4e/SKYmmKPY/3uX7uvVTTCjYEMZHBac7W+b100roCYhdzfk23+HgBzz+bVn0nZ0JnKPD5PFmjD6GN3R40+wlfrD6u3i72pzk/NJf85CMFk947YBAt/NrXQeG9A=
